title: JSERA
description: JSERA Introduction Page
theme: just-the-docs

url: https://jsera001.github.io
aux_links:
  Template Repository: https://github.com/jsera001/jsera001.github.io

default:
  - jekyll-default-layout

color_scheme: dark


collections:
  tests:
    output: true
  tutorials:
    output: true

just_the_docs:
  collections:
    tests:
      name: Tests
      search_exclude: true
    tutorials:
      name: Tutorials
      nav_fold: true