title: JSERA
description: JSERA Introduction Page
theme: just-the-docs

url: https://jsera001.github.io
aux_links:
  Template Repository: https://github.com/jsera001/jsera001.github.io

default:
  - jekyll-default-layout

color_scheme: dark


collections:
  education:
    output: true
  projects:
    output: true
  publications:
    output: true
  cv:
    output: true

just_the_docs:
  collections:
    education:
      name: Education 
      search_exclude: false
      nav_fold: false
    projects:
      name: Projects
      nav_fold: true
    publications:
      name: Publications
      nav_fold: true
    cv:
      name: CV
      nav_fold: false